---
# Node Ready: type = ready, status = True
# Node NotReady: type = ready, status = Unknown
- name: See if node is in ready state
  shell: >-
     kubectl get node {{ inventory_hostname }}
     -o jsonpath='{ range .status.conditions[?(@.type == "Ready")].status }{ @ }{ end }'
  register: kubectl_node_ready
  delegate_to: "localhost"
  failed_when: false
  changed_when: false

# SchedulingDisabled: unschedulable = true
# else unschedulable key doesn't exist
- name: See if node is schedulable
  shell: >-
     kubectl get node {{ inventory_hostname }}
     -o jsonpath='{ .spec.unschedulable }'
  register: kubectl_node_schedulable
  delegate_to: "localhost"
  failed_when: false
  changed_when: false

- name: Uncordon node
  command: "kubectl uncordon {{ inventory_hostname }}"
  delegate_to: "localhost"
